// Package secureconfig provides the plugin with a secure API to interact with Ambient.
package secureconfig

import (
	"net/http"

	"github.com/ambientkit/ambient"
	"github.com/ambientkit/ambient/internal/config"
	"github.com/ambientkit/ambient/internal/routerecorder"
)

//go:generate go run github.com/vburenin/ifacemaker -f *.go -s SecureSite -i SecureSite -p ambient -o ../../gen_securesite.go -y "SecureSite provides plugin functions." -c "Code generated by ifacemaker. DO NOT EDIT."

// SecureSite is a secure data access for the site.
type SecureSite struct {
	pluginName string

	log          ambient.AppLogger
	pluginsystem ambient.PluginSystem
	sess         ambient.AppSession
	mux          ambient.AppRouter
	render       ambient.Renderer
	recorder     *routerecorder.RouteRecorder
}

// NewSecureSite returns a new secure site.
func NewSecureSite(pluginName string, log ambient.AppLogger, ps ambient.PluginSystem,
	session ambient.AppSession, mux ambient.AppRouter, render ambient.Renderer, recorder *routerecorder.RouteRecorder) *SecureSite {
	return &SecureSite{
		pluginName: pluginName,

		log:          log,
		sess:         session,
		mux:          mux,
		pluginsystem: ps,
		render:       render,
		recorder:     recorder,
	}
}

// Error handles returning the proper error.
func (ss *SecureSite) Error(siteError error) (status int, err error) {
	switch siteError {
	case config.ErrAccessDenied, config.ErrGrantNotRequested, config.ErrSettingNotSpecified:
		return http.StatusForbidden, siteError
	case config.ErrNotFound:
		return http.StatusNotFound, siteError
	default:
		return http.StatusInternalServerError, siteError
	}
}

// Load forces a reload of the data.
func (ss *SecureSite) Load() error {
	if !ss.Authorized(ambient.GrantSiteLoadTrigger) {
		return config.ErrAccessDenied
	}

	return ss.pluginsystem.Load()
}

// Authorized determines if the current context has access.
func (ss *SecureSite) Authorized(grant ambient.Grant) bool {
	return ss.pluginsystem.Authorized(ss.pluginName, grant)
}
