// Code generated by ifacemaker. DO NOT EDIT.

package ambient

// GRPCSystem manages connecting, loading, monitoring, and disconnecting gRPC plugins..
type GRPCSystem interface {
	// Monitor starts monitoring the gRPC plugins.
	Monitor()
	// ConnectAll will connect to all gRPC plugins in the plugin system.
	ConnectAll()
	// Connect will connect to a new gRPC plugin.
	Connect(p Plugin, middleware bool)
	// Disconnect stops the gRPC clients.
	Disconnect()
	// MonitorGRPCClients will restart clients if they crash.
	MonitorGRPCClients()
}
