// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: site.proto

package protodef

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SiteAuthorizedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grant string `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
}

func (x *SiteAuthorizedRequest) Reset() {
	*x = SiteAuthorizedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteAuthorizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteAuthorizedRequest) ProtoMessage() {}

func (x *SiteAuthorizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteAuthorizedRequest.ProtoReflect.Descriptor instead.
func (*SiteAuthorizedRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{0}
}

func (x *SiteAuthorizedRequest) GetGrant() string {
	if x != nil {
		return x.Grant
	}
	return ""
}

type SiteAuthorizedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorized bool `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
}

func (x *SiteAuthorizedResponse) Reset() {
	*x = SiteAuthorizedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteAuthorizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteAuthorizedResponse) ProtoMessage() {}

func (x *SiteAuthorizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteAuthorizedResponse.ProtoReflect.Descriptor instead.
func (*SiteAuthorizedResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{1}
}

func (x *SiteAuthorizedResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type SiteUserLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requestid string `protobuf:"bytes,1,opt,name=requestid,proto3" json:"requestid,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SiteUserLoginRequest) Reset() {
	*x = SiteUserLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteUserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteUserLoginRequest) ProtoMessage() {}

func (x *SiteUserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteUserLoginRequest.ProtoReflect.Descriptor instead.
func (*SiteUserLoginRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{2}
}

func (x *SiteUserLoginRequest) GetRequestid() string {
	if x != nil {
		return x.Requestid
	}
	return ""
}

func (x *SiteUserLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SiteAuthenticatedUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requestid string `protobuf:"bytes,1,opt,name=requestid,proto3" json:"requestid,omitempty"`
}

func (x *SiteAuthenticatedUserRequest) Reset() {
	*x = SiteAuthenticatedUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteAuthenticatedUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteAuthenticatedUserRequest) ProtoMessage() {}

func (x *SiteAuthenticatedUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteAuthenticatedUserRequest.ProtoReflect.Descriptor instead.
func (*SiteAuthenticatedUserRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{3}
}

func (x *SiteAuthenticatedUserRequest) GetRequestid() string {
	if x != nil {
		return x.Requestid
	}
	return ""
}

type SiteAuthenticatedUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SiteAuthenticatedUserResponse) Reset() {
	*x = SiteAuthenticatedUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteAuthenticatedUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteAuthenticatedUserResponse) ProtoMessage() {}

func (x *SiteAuthenticatedUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteAuthenticatedUserResponse.ProtoReflect.Descriptor instead.
func (*SiteAuthenticatedUserResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{4}
}

func (x *SiteAuthenticatedUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_site_proto protoreflect.FileDescriptor

var file_site_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x6d,
	0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x1a, 0x0b,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x15, 0x53,
	0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x16, 0x53, 0x69,
	0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x64, 0x22, 0x50, 0x0a, 0x14, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x1c, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x1d, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x32, 0xed, 0x02, 0x0a, 0x04, 0x53, 0x69, 0x74, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x4c, 0x6f,
	0x61, 0x64, 0x12, 0x17, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x61, 0x6d,
	0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x64, 0x12, 0x27, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66,
	0x2e, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x11, 0x41, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2e,
	0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65,
	0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f,
	0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65,
	0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_site_proto_rawDescOnce sync.Once
	file_site_proto_rawDescData = file_site_proto_rawDesc
)

func file_site_proto_rawDescGZIP() []byte {
	file_site_proto_rawDescOnce.Do(func() {
		file_site_proto_rawDescData = protoimpl.X.CompressGZIP(file_site_proto_rawDescData)
	})
	return file_site_proto_rawDescData
}

var file_site_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_site_proto_goTypes = []interface{}{
	(*SiteAuthorizedRequest)(nil),         // 0: ambient.protodef.SiteAuthorizedRequest
	(*SiteAuthorizedResponse)(nil),        // 1: ambient.protodef.SiteAuthorizedResponse
	(*SiteUserLoginRequest)(nil),          // 2: ambient.protodef.SiteUserLoginRequest
	(*SiteAuthenticatedUserRequest)(nil),  // 3: ambient.protodef.SiteAuthenticatedUserRequest
	(*SiteAuthenticatedUserResponse)(nil), // 4: ambient.protodef.SiteAuthenticatedUserResponse
	(*Empty)(nil),                         // 5: ambient.protodef.Empty
}
var file_site_proto_depIdxs = []int32{
	5, // 0: ambient.protodef.Site.Load:input_type -> ambient.protodef.Empty
	0, // 1: ambient.protodef.Site.Authorized:input_type -> ambient.protodef.SiteAuthorizedRequest
	2, // 2: ambient.protodef.Site.UserLogin:input_type -> ambient.protodef.SiteUserLoginRequest
	3, // 3: ambient.protodef.Site.AuthenticatedUser:input_type -> ambient.protodef.SiteAuthenticatedUserRequest
	5, // 4: ambient.protodef.Site.Load:output_type -> ambient.protodef.Empty
	1, // 5: ambient.protodef.Site.Authorized:output_type -> ambient.protodef.SiteAuthorizedResponse
	5, // 6: ambient.protodef.Site.UserLogin:output_type -> ambient.protodef.Empty
	4, // 7: ambient.protodef.Site.AuthenticatedUser:output_type -> ambient.protodef.SiteAuthenticatedUserResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_site_proto_init() }
func file_site_proto_init() {
	if File_site_proto != nil {
		return
	}
	file_empty_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_site_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteAuthorizedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteAuthorizedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteUserLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteAuthenticatedUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteAuthenticatedUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_site_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_site_proto_goTypes,
		DependencyIndexes: file_site_proto_depIdxs,
		MessageInfos:      file_site_proto_msgTypes,
	}.Build()
	File_site_proto = out.File
	file_site_proto_rawDesc = nil
	file_site_proto_goTypes = nil
	file_site_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SiteClient is the client API for Site service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SiteClient interface {
	// rpc Error(SiteErrorRequest) returns (SiteErrorResponse) {}
	Load(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Authorized(ctx context.Context, in *SiteAuthorizedRequest, opts ...grpc.CallOption) (*SiteAuthorizedResponse, error)
	UserLogin(ctx context.Context, in *SiteUserLoginRequest, opts ...grpc.CallOption) (*Empty, error)
	AuthenticatedUser(ctx context.Context, in *SiteAuthenticatedUserRequest, opts ...grpc.CallOption) (*SiteAuthenticatedUserResponse, error)
}

type siteClient struct {
	cc grpc.ClientConnInterface
}

func NewSiteClient(cc grpc.ClientConnInterface) SiteClient {
	return &siteClient{cc}
}

func (c *siteClient) Load(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) Authorized(ctx context.Context, in *SiteAuthorizedRequest, opts ...grpc.CallOption) (*SiteAuthorizedResponse, error) {
	out := new(SiteAuthorizedResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/Authorized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) UserLogin(ctx context.Context, in *SiteUserLoginRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) AuthenticatedUser(ctx context.Context, in *SiteAuthenticatedUserRequest, opts ...grpc.CallOption) (*SiteAuthenticatedUserResponse, error) {
	out := new(SiteAuthenticatedUserResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/AuthenticatedUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiteServer is the server API for Site service.
type SiteServer interface {
	// rpc Error(SiteErrorRequest) returns (SiteErrorResponse) {}
	Load(context.Context, *Empty) (*Empty, error)
	Authorized(context.Context, *SiteAuthorizedRequest) (*SiteAuthorizedResponse, error)
	UserLogin(context.Context, *SiteUserLoginRequest) (*Empty, error)
	AuthenticatedUser(context.Context, *SiteAuthenticatedUserRequest) (*SiteAuthenticatedUserResponse, error)
}

// UnimplementedSiteServer can be embedded to have forward compatible implementations.
type UnimplementedSiteServer struct {
}

func (*UnimplementedSiteServer) Load(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedSiteServer) Authorized(context.Context, *SiteAuthorizedRequest) (*SiteAuthorizedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorized not implemented")
}
func (*UnimplementedSiteServer) UserLogin(context.Context, *SiteUserLoginRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (*UnimplementedSiteServer) AuthenticatedUser(context.Context, *SiteAuthenticatedUserRequest) (*SiteAuthenticatedUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticatedUser not implemented")
}

func RegisterSiteServer(s *grpc.Server, srv SiteServer) {
	s.RegisterService(&_Site_serviceDesc, srv)
}

func _Site_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).Load(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_Authorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteAuthorizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).Authorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/Authorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).Authorized(ctx, req.(*SiteAuthorizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteUserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/UserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).UserLogin(ctx, req.(*SiteUserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_AuthenticatedUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteAuthenticatedUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).AuthenticatedUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/AuthenticatedUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).AuthenticatedUser(ctx, req.(*SiteAuthenticatedUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Site_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ambient.protodef.Site",
	HandlerType: (*SiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _Site_Load_Handler,
		},
		{
			MethodName: "Authorized",
			Handler:    _Site_Authorized_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _Site_UserLogin_Handler,
		},
		{
			MethodName: "AuthenticatedUser",
			Handler:    _Site_AuthenticatedUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "site.proto",
}
