// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: site.proto

package protodef

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SiteAuthorizedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grant string `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
}

func (x *SiteAuthorizedRequest) Reset() {
	*x = SiteAuthorizedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteAuthorizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteAuthorizedRequest) ProtoMessage() {}

func (x *SiteAuthorizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteAuthorizedRequest.ProtoReflect.Descriptor instead.
func (*SiteAuthorizedRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{0}
}

func (x *SiteAuthorizedRequest) GetGrant() string {
	if x != nil {
		return x.Grant
	}
	return ""
}

type SiteAuthorizedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorized bool `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
}

func (x *SiteAuthorizedResponse) Reset() {
	*x = SiteAuthorizedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteAuthorizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteAuthorizedResponse) ProtoMessage() {}

func (x *SiteAuthorizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteAuthorizedResponse.ProtoReflect.Descriptor instead.
func (*SiteAuthorizedResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{1}
}

func (x *SiteAuthorizedResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type SiteNeighborPluginGrantListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pluginname string `protobuf:"bytes,1,opt,name=pluginname,proto3" json:"pluginname,omitempty"`
}

func (x *SiteNeighborPluginGrantListRequest) Reset() {
	*x = SiteNeighborPluginGrantListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteNeighborPluginGrantListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteNeighborPluginGrantListRequest) ProtoMessage() {}

func (x *SiteNeighborPluginGrantListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteNeighborPluginGrantListRequest.ProtoReflect.Descriptor instead.
func (*SiteNeighborPluginGrantListRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{2}
}

func (x *SiteNeighborPluginGrantListRequest) GetPluginname() string {
	if x != nil {
		return x.Pluginname
	}
	return ""
}

type SiteNeighborPluginGrantListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grants []*GrantRequest `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
}

func (x *SiteNeighborPluginGrantListResponse) Reset() {
	*x = SiteNeighborPluginGrantListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteNeighborPluginGrantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteNeighborPluginGrantListResponse) ProtoMessage() {}

func (x *SiteNeighborPluginGrantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteNeighborPluginGrantListResponse.ProtoReflect.Descriptor instead.
func (*SiteNeighborPluginGrantListResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{3}
}

func (x *SiteNeighborPluginGrantListResponse) GetGrants() []*GrantRequest {
	if x != nil {
		return x.Grants
	}
	return nil
}

type SiteNeighborPluginGrantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pluginname string `protobuf:"bytes,1,opt,name=pluginname,proto3" json:"pluginname,omitempty"`
}

func (x *SiteNeighborPluginGrantsRequest) Reset() {
	*x = SiteNeighborPluginGrantsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteNeighborPluginGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteNeighborPluginGrantsRequest) ProtoMessage() {}

func (x *SiteNeighborPluginGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteNeighborPluginGrantsRequest.ProtoReflect.Descriptor instead.
func (*SiteNeighborPluginGrantsRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{4}
}

func (x *SiteNeighborPluginGrantsRequest) GetPluginname() string {
	if x != nil {
		return x.Pluginname
	}
	return ""
}

type SiteNeighborPluginGrantsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grants *structpb.Struct `protobuf:"bytes,1,opt,name=grants,proto3" json:"grants,omitempty"`
}

func (x *SiteNeighborPluginGrantsResponse) Reset() {
	*x = SiteNeighborPluginGrantsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteNeighborPluginGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteNeighborPluginGrantsResponse) ProtoMessage() {}

func (x *SiteNeighborPluginGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteNeighborPluginGrantsResponse.ProtoReflect.Descriptor instead.
func (*SiteNeighborPluginGrantsResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{5}
}

func (x *SiteNeighborPluginGrantsResponse) GetGrants() *structpb.Struct {
	if x != nil {
		return x.Grants
	}
	return nil
}

type SiteNeighborPluginGrantedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pluginname string `protobuf:"bytes,1,opt,name=pluginname,proto3" json:"pluginname,omitempty"`
	Grant      string `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
}

func (x *SiteNeighborPluginGrantedRequest) Reset() {
	*x = SiteNeighborPluginGrantedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteNeighborPluginGrantedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteNeighborPluginGrantedRequest) ProtoMessage() {}

func (x *SiteNeighborPluginGrantedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteNeighborPluginGrantedRequest.ProtoReflect.Descriptor instead.
func (*SiteNeighborPluginGrantedRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{6}
}

func (x *SiteNeighborPluginGrantedRequest) GetPluginname() string {
	if x != nil {
		return x.Pluginname
	}
	return ""
}

func (x *SiteNeighborPluginGrantedRequest) GetGrant() string {
	if x != nil {
		return x.Grant
	}
	return ""
}

type SiteNeighborPluginGrantedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Granted bool `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
}

func (x *SiteNeighborPluginGrantedResponse) Reset() {
	*x = SiteNeighborPluginGrantedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteNeighborPluginGrantedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteNeighborPluginGrantedResponse) ProtoMessage() {}

func (x *SiteNeighborPluginGrantedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteNeighborPluginGrantedResponse.ProtoReflect.Descriptor instead.
func (*SiteNeighborPluginGrantedResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{7}
}

func (x *SiteNeighborPluginGrantedResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type SiteNeighborPluginRequestedGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pluginname string `protobuf:"bytes,1,opt,name=pluginname,proto3" json:"pluginname,omitempty"`
	Grant      string `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
}

func (x *SiteNeighborPluginRequestedGrantRequest) Reset() {
	*x = SiteNeighborPluginRequestedGrantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteNeighborPluginRequestedGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteNeighborPluginRequestedGrantRequest) ProtoMessage() {}

func (x *SiteNeighborPluginRequestedGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteNeighborPluginRequestedGrantRequest.ProtoReflect.Descriptor instead.
func (*SiteNeighborPluginRequestedGrantRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{8}
}

func (x *SiteNeighborPluginRequestedGrantRequest) GetPluginname() string {
	if x != nil {
		return x.Pluginname
	}
	return ""
}

func (x *SiteNeighborPluginRequestedGrantRequest) GetGrant() string {
	if x != nil {
		return x.Grant
	}
	return ""
}

type SiteNeighborPluginRequestedGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Granted bool `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
}

func (x *SiteNeighborPluginRequestedGrantResponse) Reset() {
	*x = SiteNeighborPluginRequestedGrantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteNeighborPluginRequestedGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteNeighborPluginRequestedGrantResponse) ProtoMessage() {}

func (x *SiteNeighborPluginRequestedGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteNeighborPluginRequestedGrantResponse.ProtoReflect.Descriptor instead.
func (*SiteNeighborPluginRequestedGrantResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{9}
}

func (x *SiteNeighborPluginRequestedGrantResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type SiteSetNeighborPluginGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pluginname string `protobuf:"bytes,1,opt,name=pluginname,proto3" json:"pluginname,omitempty"`
	Grant      string `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	Granted    bool   `protobuf:"varint,3,opt,name=granted,proto3" json:"granted,omitempty"`
}

func (x *SiteSetNeighborPluginGrantRequest) Reset() {
	*x = SiteSetNeighborPluginGrantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteSetNeighborPluginGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSetNeighborPluginGrantRequest) ProtoMessage() {}

func (x *SiteSetNeighborPluginGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSetNeighborPluginGrantRequest.ProtoReflect.Descriptor instead.
func (*SiteSetNeighborPluginGrantRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{10}
}

func (x *SiteSetNeighborPluginGrantRequest) GetPluginname() string {
	if x != nil {
		return x.Pluginname
	}
	return ""
}

func (x *SiteSetNeighborPluginGrantRequest) GetGrant() string {
	if x != nil {
		return x.Grant
	}
	return ""
}

func (x *SiteSetNeighborPluginGrantRequest) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type SitePluginsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugindata *structpb.Struct `protobuf:"bytes,1,opt,name=plugindata,proto3" json:"plugindata,omitempty"`
}

func (x *SitePluginsResponse) Reset() {
	*x = SitePluginsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SitePluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SitePluginsResponse) ProtoMessage() {}

func (x *SitePluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SitePluginsResponse.ProtoReflect.Descriptor instead.
func (*SitePluginsResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{11}
}

func (x *SitePluginsResponse) GetPlugindata() *structpb.Struct {
	if x != nil {
		return x.Plugindata
	}
	return nil
}

type SitePluginNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *SitePluginNamesResponse) Reset() {
	*x = SitePluginNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SitePluginNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SitePluginNamesResponse) ProtoMessage() {}

func (x *SitePluginNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SitePluginNamesResponse.ProtoReflect.Descriptor instead.
func (*SitePluginNamesResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{12}
}

func (x *SitePluginNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SiteDeletePluginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SiteDeletePluginRequest) Reset() {
	*x = SiteDeletePluginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteDeletePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteDeletePluginRequest) ProtoMessage() {}

func (x *SiteDeletePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteDeletePluginRequest.ProtoReflect.Descriptor instead.
func (*SiteDeletePluginRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{13}
}

func (x *SiteDeletePluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SiteEnablePluginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Load bool   `protobuf:"varint,2,opt,name=load,proto3" json:"load,omitempty"`
}

func (x *SiteEnablePluginRequest) Reset() {
	*x = SiteEnablePluginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteEnablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteEnablePluginRequest) ProtoMessage() {}

func (x *SiteEnablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteEnablePluginRequest.ProtoReflect.Descriptor instead.
func (*SiteEnablePluginRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{14}
}

func (x *SiteEnablePluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SiteEnablePluginRequest) GetLoad() bool {
	if x != nil {
		return x.Load
	}
	return false
}

type SiteDisablePluginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Unload bool   `protobuf:"varint,2,opt,name=unload,proto3" json:"unload,omitempty"`
}

func (x *SiteDisablePluginRequest) Reset() {
	*x = SiteDisablePluginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteDisablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteDisablePluginRequest) ProtoMessage() {}

func (x *SiteDisablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteDisablePluginRequest.ProtoReflect.Descriptor instead.
func (*SiteDisablePluginRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{15}
}

func (x *SiteDisablePluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SiteDisablePluginRequest) GetUnload() bool {
	if x != nil {
		return x.Unload
	}
	return false
}

type SiteUserLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requestid string `protobuf:"bytes,1,opt,name=requestid,proto3" json:"requestid,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SiteUserLoginRequest) Reset() {
	*x = SiteUserLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteUserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteUserLoginRequest) ProtoMessage() {}

func (x *SiteUserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteUserLoginRequest.ProtoReflect.Descriptor instead.
func (*SiteUserLoginRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{16}
}

func (x *SiteUserLoginRequest) GetRequestid() string {
	if x != nil {
		return x.Requestid
	}
	return ""
}

func (x *SiteUserLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SiteAuthenticatedUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requestid string `protobuf:"bytes,1,opt,name=requestid,proto3" json:"requestid,omitempty"`
}

func (x *SiteAuthenticatedUserRequest) Reset() {
	*x = SiteAuthenticatedUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteAuthenticatedUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteAuthenticatedUserRequest) ProtoMessage() {}

func (x *SiteAuthenticatedUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteAuthenticatedUserRequest.ProtoReflect.Descriptor instead.
func (*SiteAuthenticatedUserRequest) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{17}
}

func (x *SiteAuthenticatedUserRequest) GetRequestid() string {
	if x != nil {
		return x.Requestid
	}
	return ""
}

type SiteAuthenticatedUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SiteAuthenticatedUserResponse) Reset() {
	*x = SiteAuthenticatedUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_site_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteAuthenticatedUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteAuthenticatedUserResponse) ProtoMessage() {}

func (x *SiteAuthenticatedUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_site_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteAuthenticatedUserResponse.ProtoReflect.Descriptor instead.
func (*SiteAuthenticatedUserResponse) Descriptor() ([]byte, []int) {
	return file_site_proto_rawDescGZIP(), []int{18}
}

func (x *SiteAuthenticatedUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_site_proto protoreflect.FileDescriptor

var file_site_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x6d,
	0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x1a, 0x0b,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x15, 0x53, 0x69, 0x74, 0x65, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x16, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64,
	0x22, 0x44, 0x0a, 0x22, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x23, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65,
	0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x06, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66,
	0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x67,
	0x72, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x41, 0x0a, 0x1f, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69,
	0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x20, 0x53, 0x69, 0x74, 0x65,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72,
	0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06,
	0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x58, 0x0a,
	0x20, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x21, 0x53, 0x69, 0x74, 0x65, 0x4e,
	0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61,
	0x6e, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x67,
	0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x22, 0x5f, 0x0a, 0x27, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65,
	0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x22, 0x44, 0x0a, 0x28, 0x53, 0x69, 0x74, 0x65, 0x4e,
	0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x22, 0x73, 0x0a,
	0x21, 0x53, 0x69, 0x74, 0x65, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x61, 0x6e,
	0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74,
	0x65, 0x64, 0x22, 0x4e, 0x0a, 0x13, 0x53, 0x69, 0x74, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x2f, 0x0a, 0x17, 0x53, 0x69, 0x74, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x17, 0x53, 0x69, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x41, 0x0a, 0x17, 0x53, 0x69, 0x74, 0x65, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x46, 0x0a, 0x18, 0x53, 0x69, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x50, 0x0a,
	0x14, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x3c, 0x0a, 0x1c, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x64, 0x22, 0x3b, 0x0a,
	0x1d, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xf2, 0x0b, 0x0a, 0x04, 0x53,
	0x69, 0x74, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x17, 0x2e, 0x61, 0x6d,
	0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x61, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x27, 0x2e,
	0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66,
	0x2e, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x88, 0x01, 0x0a, 0x17, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34,
	0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65,
	0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7f, 0x0a,
	0x14, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x31, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69,
	0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72,
	0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x82,
	0x01, 0x0a, 0x15, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x32, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x72,
	0x61, 0x6e, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x61,
	0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e,
	0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x97, 0x01, 0x0a, 0x1c, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x12, 0x39, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x3a, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64,
	0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x47, 0x72,
	0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a,
	0x16, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x33, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x53,
	0x65, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61,
	0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x07, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x73, 0x12, 0x17, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x25, 0x2e, 0x61, 0x6d,
	0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53,
	0x69, 0x74, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x29, 0x2e, 0x61,
	0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e,
	0x53, 0x69, 0x74, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x29, 0x2e, 0x61, 0x6d, 0x62, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74,
	0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x54, 0x0a, 0x0c, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12,
	0x29, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64,
	0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x6d, 0x62,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x12, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x6c, 0x6c,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x61, 0x6d,
	0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x56, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x12, 0x2a, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61,
	0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x2e, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61,
	0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2e, 0x2e, 0x61,
	0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e,
	0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x61,
	0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e,
	0x53, 0x69, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_site_proto_rawDescOnce sync.Once
	file_site_proto_rawDescData = file_site_proto_rawDesc
)

func file_site_proto_rawDescGZIP() []byte {
	file_site_proto_rawDescOnce.Do(func() {
		file_site_proto_rawDescData = protoimpl.X.CompressGZIP(file_site_proto_rawDescData)
	})
	return file_site_proto_rawDescData
}

var file_site_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_site_proto_goTypes = []interface{}{
	(*SiteAuthorizedRequest)(nil),                    // 0: ambient.protodef.SiteAuthorizedRequest
	(*SiteAuthorizedResponse)(nil),                   // 1: ambient.protodef.SiteAuthorizedResponse
	(*SiteNeighborPluginGrantListRequest)(nil),       // 2: ambient.protodef.SiteNeighborPluginGrantListRequest
	(*SiteNeighborPluginGrantListResponse)(nil),      // 3: ambient.protodef.SiteNeighborPluginGrantListResponse
	(*SiteNeighborPluginGrantsRequest)(nil),          // 4: ambient.protodef.SiteNeighborPluginGrantsRequest
	(*SiteNeighborPluginGrantsResponse)(nil),         // 5: ambient.protodef.SiteNeighborPluginGrantsResponse
	(*SiteNeighborPluginGrantedRequest)(nil),         // 6: ambient.protodef.SiteNeighborPluginGrantedRequest
	(*SiteNeighborPluginGrantedResponse)(nil),        // 7: ambient.protodef.SiteNeighborPluginGrantedResponse
	(*SiteNeighborPluginRequestedGrantRequest)(nil),  // 8: ambient.protodef.SiteNeighborPluginRequestedGrantRequest
	(*SiteNeighborPluginRequestedGrantResponse)(nil), // 9: ambient.protodef.SiteNeighborPluginRequestedGrantResponse
	(*SiteSetNeighborPluginGrantRequest)(nil),        // 10: ambient.protodef.SiteSetNeighborPluginGrantRequest
	(*SitePluginsResponse)(nil),                      // 11: ambient.protodef.SitePluginsResponse
	(*SitePluginNamesResponse)(nil),                  // 12: ambient.protodef.SitePluginNamesResponse
	(*SiteDeletePluginRequest)(nil),                  // 13: ambient.protodef.SiteDeletePluginRequest
	(*SiteEnablePluginRequest)(nil),                  // 14: ambient.protodef.SiteEnablePluginRequest
	(*SiteDisablePluginRequest)(nil),                 // 15: ambient.protodef.SiteDisablePluginRequest
	(*SiteUserLoginRequest)(nil),                     // 16: ambient.protodef.SiteUserLoginRequest
	(*SiteAuthenticatedUserRequest)(nil),             // 17: ambient.protodef.SiteAuthenticatedUserRequest
	(*SiteAuthenticatedUserResponse)(nil),            // 18: ambient.protodef.SiteAuthenticatedUserResponse
	(*GrantRequest)(nil),                             // 19: ambient.protodef.GrantRequest
	(*structpb.Struct)(nil),                          // 20: google.protobuf.Struct
	(*Empty)(nil),                                    // 21: ambient.protodef.Empty
}
var file_site_proto_depIdxs = []int32{
	19, // 0: ambient.protodef.SiteNeighborPluginGrantListResponse.grants:type_name -> ambient.protodef.GrantRequest
	20, // 1: ambient.protodef.SiteNeighborPluginGrantsResponse.grants:type_name -> google.protobuf.Struct
	20, // 2: ambient.protodef.SitePluginsResponse.plugindata:type_name -> google.protobuf.Struct
	21, // 3: ambient.protodef.Site.Load:input_type -> ambient.protodef.Empty
	0,  // 4: ambient.protodef.Site.Authorized:input_type -> ambient.protodef.SiteAuthorizedRequest
	2,  // 5: ambient.protodef.Site.NeighborPluginGrantList:input_type -> ambient.protodef.SiteNeighborPluginGrantListRequest
	4,  // 6: ambient.protodef.Site.NeighborPluginGrants:input_type -> ambient.protodef.SiteNeighborPluginGrantsRequest
	6,  // 7: ambient.protodef.Site.NeighborPluginGranted:input_type -> ambient.protodef.SiteNeighborPluginGrantedRequest
	8,  // 8: ambient.protodef.Site.NeighborPluginRequestedGrant:input_type -> ambient.protodef.SiteNeighborPluginRequestedGrantRequest
	10, // 9: ambient.protodef.Site.SetNeighborPluginGrant:input_type -> ambient.protodef.SiteSetNeighborPluginGrantRequest
	21, // 10: ambient.protodef.Site.Plugins:input_type -> ambient.protodef.Empty
	21, // 11: ambient.protodef.Site.PluginNames:input_type -> ambient.protodef.Empty
	13, // 12: ambient.protodef.Site.DeletePlugin:input_type -> ambient.protodef.SiteDeletePluginRequest
	14, // 13: ambient.protodef.Site.EnablePlugin:input_type -> ambient.protodef.SiteEnablePluginRequest
	21, // 14: ambient.protodef.Site.LoadAllPluginPages:input_type -> ambient.protodef.Empty
	15, // 15: ambient.protodef.Site.DisablePlugin:input_type -> ambient.protodef.SiteDisablePluginRequest
	16, // 16: ambient.protodef.Site.UserLogin:input_type -> ambient.protodef.SiteUserLoginRequest
	17, // 17: ambient.protodef.Site.AuthenticatedUser:input_type -> ambient.protodef.SiteAuthenticatedUserRequest
	21, // 18: ambient.protodef.Site.Load:output_type -> ambient.protodef.Empty
	1,  // 19: ambient.protodef.Site.Authorized:output_type -> ambient.protodef.SiteAuthorizedResponse
	3,  // 20: ambient.protodef.Site.NeighborPluginGrantList:output_type -> ambient.protodef.SiteNeighborPluginGrantListResponse
	5,  // 21: ambient.protodef.Site.NeighborPluginGrants:output_type -> ambient.protodef.SiteNeighborPluginGrantsResponse
	7,  // 22: ambient.protodef.Site.NeighborPluginGranted:output_type -> ambient.protodef.SiteNeighborPluginGrantedResponse
	9,  // 23: ambient.protodef.Site.NeighborPluginRequestedGrant:output_type -> ambient.protodef.SiteNeighborPluginRequestedGrantResponse
	21, // 24: ambient.protodef.Site.SetNeighborPluginGrant:output_type -> ambient.protodef.Empty
	11, // 25: ambient.protodef.Site.Plugins:output_type -> ambient.protodef.SitePluginsResponse
	12, // 26: ambient.protodef.Site.PluginNames:output_type -> ambient.protodef.SitePluginNamesResponse
	21, // 27: ambient.protodef.Site.DeletePlugin:output_type -> ambient.protodef.Empty
	21, // 28: ambient.protodef.Site.EnablePlugin:output_type -> ambient.protodef.Empty
	21, // 29: ambient.protodef.Site.LoadAllPluginPages:output_type -> ambient.protodef.Empty
	21, // 30: ambient.protodef.Site.DisablePlugin:output_type -> ambient.protodef.Empty
	21, // 31: ambient.protodef.Site.UserLogin:output_type -> ambient.protodef.Empty
	18, // 32: ambient.protodef.Site.AuthenticatedUser:output_type -> ambient.protodef.SiteAuthenticatedUserResponse
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_site_proto_init() }
func file_site_proto_init() {
	if File_site_proto != nil {
		return
	}
	file_empty_proto_init()
	file_plugin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_site_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteAuthorizedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteAuthorizedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteNeighborPluginGrantListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteNeighborPluginGrantListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteNeighborPluginGrantsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteNeighborPluginGrantsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteNeighborPluginGrantedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteNeighborPluginGrantedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteNeighborPluginRequestedGrantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteNeighborPluginRequestedGrantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteSetNeighborPluginGrantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SitePluginsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SitePluginNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteDeletePluginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteEnablePluginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteDisablePluginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteUserLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteAuthenticatedUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_site_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteAuthenticatedUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_site_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_site_proto_goTypes,
		DependencyIndexes: file_site_proto_depIdxs,
		MessageInfos:      file_site_proto_msgTypes,
	}.Build()
	File_site_proto = out.File
	file_site_proto_rawDesc = nil
	file_site_proto_goTypes = nil
	file_site_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SiteClient is the client API for Site service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SiteClient interface {
	// rpc Error(SiteErrorRequest) returns (SiteErrorResponse) {}
	Load(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Authorized(ctx context.Context, in *SiteAuthorizedRequest, opts ...grpc.CallOption) (*SiteAuthorizedResponse, error)
	NeighborPluginGrantList(ctx context.Context, in *SiteNeighborPluginGrantListRequest, opts ...grpc.CallOption) (*SiteNeighborPluginGrantListResponse, error)
	NeighborPluginGrants(ctx context.Context, in *SiteNeighborPluginGrantsRequest, opts ...grpc.CallOption) (*SiteNeighborPluginGrantsResponse, error)
	NeighborPluginGranted(ctx context.Context, in *SiteNeighborPluginGrantedRequest, opts ...grpc.CallOption) (*SiteNeighborPluginGrantedResponse, error)
	NeighborPluginRequestedGrant(ctx context.Context, in *SiteNeighborPluginRequestedGrantRequest, opts ...grpc.CallOption) (*SiteNeighborPluginRequestedGrantResponse, error)
	SetNeighborPluginGrant(ctx context.Context, in *SiteSetNeighborPluginGrantRequest, opts ...grpc.CallOption) (*Empty, error)
	Plugins(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SitePluginsResponse, error)
	PluginNames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SitePluginNamesResponse, error)
	DeletePlugin(ctx context.Context, in *SiteDeletePluginRequest, opts ...grpc.CallOption) (*Empty, error)
	EnablePlugin(ctx context.Context, in *SiteEnablePluginRequest, opts ...grpc.CallOption) (*Empty, error)
	LoadAllPluginPages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	DisablePlugin(ctx context.Context, in *SiteDisablePluginRequest, opts ...grpc.CallOption) (*Empty, error)
	UserLogin(ctx context.Context, in *SiteUserLoginRequest, opts ...grpc.CallOption) (*Empty, error)
	AuthenticatedUser(ctx context.Context, in *SiteAuthenticatedUserRequest, opts ...grpc.CallOption) (*SiteAuthenticatedUserResponse, error)
}

type siteClient struct {
	cc grpc.ClientConnInterface
}

func NewSiteClient(cc grpc.ClientConnInterface) SiteClient {
	return &siteClient{cc}
}

func (c *siteClient) Load(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) Authorized(ctx context.Context, in *SiteAuthorizedRequest, opts ...grpc.CallOption) (*SiteAuthorizedResponse, error) {
	out := new(SiteAuthorizedResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/Authorized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) NeighborPluginGrantList(ctx context.Context, in *SiteNeighborPluginGrantListRequest, opts ...grpc.CallOption) (*SiteNeighborPluginGrantListResponse, error) {
	out := new(SiteNeighborPluginGrantListResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/NeighborPluginGrantList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) NeighborPluginGrants(ctx context.Context, in *SiteNeighborPluginGrantsRequest, opts ...grpc.CallOption) (*SiteNeighborPluginGrantsResponse, error) {
	out := new(SiteNeighborPluginGrantsResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/NeighborPluginGrants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) NeighborPluginGranted(ctx context.Context, in *SiteNeighborPluginGrantedRequest, opts ...grpc.CallOption) (*SiteNeighborPluginGrantedResponse, error) {
	out := new(SiteNeighborPluginGrantedResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/NeighborPluginGranted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) NeighborPluginRequestedGrant(ctx context.Context, in *SiteNeighborPluginRequestedGrantRequest, opts ...grpc.CallOption) (*SiteNeighborPluginRequestedGrantResponse, error) {
	out := new(SiteNeighborPluginRequestedGrantResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/NeighborPluginRequestedGrant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) SetNeighborPluginGrant(ctx context.Context, in *SiteSetNeighborPluginGrantRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/SetNeighborPluginGrant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) Plugins(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SitePluginsResponse, error) {
	out := new(SitePluginsResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/Plugins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) PluginNames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SitePluginNamesResponse, error) {
	out := new(SitePluginNamesResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/PluginNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) DeletePlugin(ctx context.Context, in *SiteDeletePluginRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/DeletePlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) EnablePlugin(ctx context.Context, in *SiteEnablePluginRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/EnablePlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) LoadAllPluginPages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/LoadAllPluginPages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) DisablePlugin(ctx context.Context, in *SiteDisablePluginRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/DisablePlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) UserLogin(ctx context.Context, in *SiteUserLoginRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) AuthenticatedUser(ctx context.Context, in *SiteAuthenticatedUserRequest, opts ...grpc.CallOption) (*SiteAuthenticatedUserResponse, error) {
	out := new(SiteAuthenticatedUserResponse)
	err := c.cc.Invoke(ctx, "/ambient.protodef.Site/AuthenticatedUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiteServer is the server API for Site service.
type SiteServer interface {
	// rpc Error(SiteErrorRequest) returns (SiteErrorResponse) {}
	Load(context.Context, *Empty) (*Empty, error)
	Authorized(context.Context, *SiteAuthorizedRequest) (*SiteAuthorizedResponse, error)
	NeighborPluginGrantList(context.Context, *SiteNeighborPluginGrantListRequest) (*SiteNeighborPluginGrantListResponse, error)
	NeighborPluginGrants(context.Context, *SiteNeighborPluginGrantsRequest) (*SiteNeighborPluginGrantsResponse, error)
	NeighborPluginGranted(context.Context, *SiteNeighborPluginGrantedRequest) (*SiteNeighborPluginGrantedResponse, error)
	NeighborPluginRequestedGrant(context.Context, *SiteNeighborPluginRequestedGrantRequest) (*SiteNeighborPluginRequestedGrantResponse, error)
	SetNeighborPluginGrant(context.Context, *SiteSetNeighborPluginGrantRequest) (*Empty, error)
	Plugins(context.Context, *Empty) (*SitePluginsResponse, error)
	PluginNames(context.Context, *Empty) (*SitePluginNamesResponse, error)
	DeletePlugin(context.Context, *SiteDeletePluginRequest) (*Empty, error)
	EnablePlugin(context.Context, *SiteEnablePluginRequest) (*Empty, error)
	LoadAllPluginPages(context.Context, *Empty) (*Empty, error)
	DisablePlugin(context.Context, *SiteDisablePluginRequest) (*Empty, error)
	UserLogin(context.Context, *SiteUserLoginRequest) (*Empty, error)
	AuthenticatedUser(context.Context, *SiteAuthenticatedUserRequest) (*SiteAuthenticatedUserResponse, error)
}

// UnimplementedSiteServer can be embedded to have forward compatible implementations.
type UnimplementedSiteServer struct {
}

func (*UnimplementedSiteServer) Load(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedSiteServer) Authorized(context.Context, *SiteAuthorizedRequest) (*SiteAuthorizedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorized not implemented")
}
func (*UnimplementedSiteServer) NeighborPluginGrantList(context.Context, *SiteNeighborPluginGrantListRequest) (*SiteNeighborPluginGrantListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NeighborPluginGrantList not implemented")
}
func (*UnimplementedSiteServer) NeighborPluginGrants(context.Context, *SiteNeighborPluginGrantsRequest) (*SiteNeighborPluginGrantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NeighborPluginGrants not implemented")
}
func (*UnimplementedSiteServer) NeighborPluginGranted(context.Context, *SiteNeighborPluginGrantedRequest) (*SiteNeighborPluginGrantedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NeighborPluginGranted not implemented")
}
func (*UnimplementedSiteServer) NeighborPluginRequestedGrant(context.Context, *SiteNeighborPluginRequestedGrantRequest) (*SiteNeighborPluginRequestedGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NeighborPluginRequestedGrant not implemented")
}
func (*UnimplementedSiteServer) SetNeighborPluginGrant(context.Context, *SiteSetNeighborPluginGrantRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNeighborPluginGrant not implemented")
}
func (*UnimplementedSiteServer) Plugins(context.Context, *Empty) (*SitePluginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Plugins not implemented")
}
func (*UnimplementedSiteServer) PluginNames(context.Context, *Empty) (*SitePluginNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginNames not implemented")
}
func (*UnimplementedSiteServer) DeletePlugin(context.Context, *SiteDeletePluginRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlugin not implemented")
}
func (*UnimplementedSiteServer) EnablePlugin(context.Context, *SiteEnablePluginRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnablePlugin not implemented")
}
func (*UnimplementedSiteServer) LoadAllPluginPages(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadAllPluginPages not implemented")
}
func (*UnimplementedSiteServer) DisablePlugin(context.Context, *SiteDisablePluginRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisablePlugin not implemented")
}
func (*UnimplementedSiteServer) UserLogin(context.Context, *SiteUserLoginRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (*UnimplementedSiteServer) AuthenticatedUser(context.Context, *SiteAuthenticatedUserRequest) (*SiteAuthenticatedUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticatedUser not implemented")
}

func RegisterSiteServer(s *grpc.Server, srv SiteServer) {
	s.RegisterService(&_Site_serviceDesc, srv)
}

func _Site_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).Load(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_Authorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteAuthorizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).Authorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/Authorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).Authorized(ctx, req.(*SiteAuthorizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_NeighborPluginGrantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteNeighborPluginGrantListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).NeighborPluginGrantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/NeighborPluginGrantList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).NeighborPluginGrantList(ctx, req.(*SiteNeighborPluginGrantListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_NeighborPluginGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteNeighborPluginGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).NeighborPluginGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/NeighborPluginGrants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).NeighborPluginGrants(ctx, req.(*SiteNeighborPluginGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_NeighborPluginGranted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteNeighborPluginGrantedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).NeighborPluginGranted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/NeighborPluginGranted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).NeighborPluginGranted(ctx, req.(*SiteNeighborPluginGrantedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_NeighborPluginRequestedGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteNeighborPluginRequestedGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).NeighborPluginRequestedGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/NeighborPluginRequestedGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).NeighborPluginRequestedGrant(ctx, req.(*SiteNeighborPluginRequestedGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_SetNeighborPluginGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteSetNeighborPluginGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).SetNeighborPluginGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/SetNeighborPluginGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).SetNeighborPluginGrant(ctx, req.(*SiteSetNeighborPluginGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_Plugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).Plugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/Plugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).Plugins(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_PluginNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).PluginNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/PluginNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).PluginNames(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_DeletePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteDeletePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).DeletePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/DeletePlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).DeletePlugin(ctx, req.(*SiteDeletePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_EnablePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteEnablePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).EnablePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/EnablePlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).EnablePlugin(ctx, req.(*SiteEnablePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_LoadAllPluginPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).LoadAllPluginPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/LoadAllPluginPages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).LoadAllPluginPages(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_DisablePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteDisablePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).DisablePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/DisablePlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).DisablePlugin(ctx, req.(*SiteDisablePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteUserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/UserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).UserLogin(ctx, req.(*SiteUserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_AuthenticatedUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteAuthenticatedUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).AuthenticatedUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambient.protodef.Site/AuthenticatedUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).AuthenticatedUser(ctx, req.(*SiteAuthenticatedUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Site_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ambient.protodef.Site",
	HandlerType: (*SiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _Site_Load_Handler,
		},
		{
			MethodName: "Authorized",
			Handler:    _Site_Authorized_Handler,
		},
		{
			MethodName: "NeighborPluginGrantList",
			Handler:    _Site_NeighborPluginGrantList_Handler,
		},
		{
			MethodName: "NeighborPluginGrants",
			Handler:    _Site_NeighborPluginGrants_Handler,
		},
		{
			MethodName: "NeighborPluginGranted",
			Handler:    _Site_NeighborPluginGranted_Handler,
		},
		{
			MethodName: "NeighborPluginRequestedGrant",
			Handler:    _Site_NeighborPluginRequestedGrant_Handler,
		},
		{
			MethodName: "SetNeighborPluginGrant",
			Handler:    _Site_SetNeighborPluginGrant_Handler,
		},
		{
			MethodName: "Plugins",
			Handler:    _Site_Plugins_Handler,
		},
		{
			MethodName: "PluginNames",
			Handler:    _Site_PluginNames_Handler,
		},
		{
			MethodName: "DeletePlugin",
			Handler:    _Site_DeletePlugin_Handler,
		},
		{
			MethodName: "EnablePlugin",
			Handler:    _Site_EnablePlugin_Handler,
		},
		{
			MethodName: "LoadAllPluginPages",
			Handler:    _Site_LoadAllPluginPages_Handler,
		},
		{
			MethodName: "DisablePlugin",
			Handler:    _Site_DisablePlugin_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _Site_UserLogin_Handler,
		},
		{
			MethodName: "AuthenticatedUser",
			Handler:    _Site_AuthenticatedUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "site.proto",
}
